const app=document.getElementById('app');
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));

const editorial={
hero:'https://unsplash.com/photos/OEgXV7S8lhI/download?force=true&w=1200',
wedding:'https://unsplash.com/photos/5-Gyzo506fg/download?force=true&w=900',
classic:'https://unsplash.com/photos/Vj6PZFCxhec/download?force=true&w=900',
casual:'https://unsplash.com/photos/qmyebfKk3pw/download?force=true&w=900',
night:'https://unsplash.com/photos/2TVr__2eMbM/download?force=true&w=900',
work:'https://unsplash.com/photos/SS1Oldoervo/download?force=true&w=900',
feminine:'https://unsplash.com/photos/pnabbBAK7ls/download?force=true&w=900'
};

const products=[
{id:'seed-column',retailer:'Seed Heritage',name:'Satin Draped Column Dress',price:249.95,sale:169.90,occasion:['wedding','night'],styles:['feminine','modern'],sizes:'4–18',colour:'Twilight Blue',url:'https://www.seedheritage.com/nz/p/satin-draped-column-dress/2605085005-TWLGHTBLUE-se.html',image:editorial.wedding},
{id:'seed-wrap',retailer:'Seed Heritage',name:'Textured Satin Wrap Shirt Dress',price:249.90,occasion:['wedding','work','night'],styles:['classic','modern'],sizes:'4–18',colour:'Coffee Bean',url:'https://www.seedheritage.com/nz/p/textured-satin-wrap-shirt-dress/2605085001-COFFEEBEAN-se.html',image:editorial.classic},
{id:'max-wrap',retailer:'Max',name:'The Wrap Dress',price:189.99,occasion:['work','wedding','night'],styles:['classic','feminine'],sizes:'Check retailer',colour:'Black Check',url:'https://www.max.co.nz/products/the-wrap-dress-328762vis-black-check',image:editorial.work},
{id:'max-lucy',retailer:'Max',name:'Lucy Bias Cut Dress',price:179.99,occasion:['wedding','night','casual'],styles:['modern','feminine'],sizes:'Check retailer',colour:'Petrol Gingham',url:'https://www.max.co.nz/products/lucy-bias-cut-dress-326229orc-petrol-gingham',image:editorial.feminine},
{id:'cr-ponte',retailer:'Country Road',name:'Panel Zip Neck Ponte Dress',price:179,occasion:['work','casual'],styles:['classic','minimal'],sizes:'4–16 listed',colour:'Check retailer',url:'https://www.countryroad.co.nz/panel-zip-neck-ponte-dress-60319061-2408',image:editorial.classic},
{id:'cr-bias',retailer:'Country Road',name:'Boat Neck Bias Dress',price:229,occasion:['wedding','night'],styles:['modern','classic'],sizes:'4–16 listed',colour:'Check retailer',url:'https://www.countryroad.co.nz/boat-neck-bias-dress-60317313-4741',image:editorial.night}
];

const looks=[
{id:1,name:'Twilight Wedding Edit',style:'modern',occasion:'wedding',items:['Satin midi dress','Refined heel','Compact bag','Gold jewellery'],price:349,score:96,visual:'wedding',image:editorial.wedding},
{id:2,name:'Classic Event Edit',style:'classic',occasion:'wedding',items:['Wrap silhouette','Neutral heel','Cream clutch','Pearl earrings'],price:330,score:93,visual:'classic',image:editorial.classic},
{id:3,name:'Soft Weekend',style:'casual',occasion:'casual',items:['Easy dress or denim','Fine knit','Leather loafer','Crossbody bag'],price:276,score:94,visual:'casual',image:editorial.casual},
{id:4,name:'Saturday After Dark',style:'modern',occasion:'night',items:['Bias dress or black denim','Satin texture','Heeled boot','Statement earrings'],price:320,score:97,visual:'night',image:editorial.night},
{id:5,name:'The Polished Workday',style:'classic',occasion:'work',items:['Clean-line dress','Structured layer','Loafer','Work tote'],price:310,score:92,visual:'work',image:editorial.work},
{id:6,name:'Lunch in Town',style:'feminine',occasion:'casual',items:['Soft midi shape','Light knit','White sneaker','Shoulder bag'],price:245,score:91,visual:'feminine',image:editorial.feminine}
];

function updateBadge(){const b=document.getElementById('savedBadge');if(b)b.textContent=get('saved',[]).length}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1900)}
function show(page){if(page==='profile')return profile();if(page==='ask')return ask();if(page==='saved')return saved();home()}
function money(n){return `NZ$${Number(n).toFixed(Number(n)%1?2:0)}`}
function shop(url){window.open(url,'_blank','noopener,noreferrer')}

function home(){app.innerHTML=`
<section class="hero hero-photo-layout">
  <div class="hero-copy"><span class="eyebrow">YOUR PERSONAL SHOPPING ASSISTANT</span><h1>Style that feels like <em>you.</em></h1><p>Build your profile once. Suited uses your size, fit preferences, style and budget to create complete looks — then connects you to real pieces from retailers.</p><div class="actions"><button class="primary large" onclick="profile()">Build my style profile</button><button class="secondary large" onclick="ask()">Ask Suited</button></div><div class="trust-row"><span class="tag">NZ sizes 6–20</span><span class="tag">Real retailer pieces</span><span class="tag">Complete outfits</span><span class="tag">Budget aware</span></div></div>
  <div class="hero-photo-wrap"><img src="${editorial.hero}" alt="Editorial fashion style inspiration"><div class="hero-photo-card"><span class="eyebrow">THE SUITED IDEA</span><strong>One profile.<br>Less scrolling.</strong><small>Illustrative style imagery · Unsplash</small></div></div>
</section>
<section class="retailer-strip"><span>LIVE V1 RETAILER EDIT</span><strong>Seed Heritage</strong><strong>Max</strong><strong>Country Road</strong><small>More retailers can be added as feeds and partnerships come online.</small></section>
<section class="home-products"><div class="section-head compact"><div><span class="eyebrow">SHOP REAL PIECES</span><h2>Current pieces Suited can recommend.</h2><p class="subtext">Real retailer names, prices and links. Editorial images are style previews only — not retailer product photography.</p></div><button class="secondary" onclick="ask()">Personalise these →</button></div><div class="product-grid">${products.slice(0,3).map(productCard).join('')}</div><p class="freshness-note">Retail prices and availability can change. V1 links you to the retailer to confirm current stock, size and final price.</p></section>`;updateBadge()}

function selected(value,current){return String(value).toLowerCase()===String(current||'').toLowerCase()?'selected':''}
function profile(){const p=get('profile',{});app.innerHTML=`<section class="panel"><span class="eyebrow">MY SUITED PROFILE</span><h1>Tell us what works for you.</h1><p class="subtext">This becomes your personal shopping brief. You can change it whenever you like, and measurements are optional.</p><div class="profile-note">V1 keeps this information on this device only. A secure account system comes with the production version.</div><form id="pf" class="form"><label>Usual NZ clothing size<select name="size">${[6,8,10,12,14,16,18,20].map(x=>`<option ${selected(x,p.size)}>${x}</option>`).join('')}</select></label><label>Height (cm)<input name="height" inputmode="numeric" value="${p.height||''}" placeholder="e.g. 168"></label><label>Bust (cm) · optional<input name="bust" inputmode="numeric" value="${p.bust||''}"></label><label>Waist (cm) · optional<input name="waist" inputmode="numeric" value="${p.waist||''}"></label><label>Hips (cm) · optional<input name="hips" inputmode="numeric" value="${p.hips||''}"></label><label>Preferred fit<select name="fit"><option ${selected('Regular',p.fit)}>Regular</option><option ${selected('Relaxed',p.fit)}>Relaxed</option><option ${selected('Fitted',p.fit)}>Fitted</option></select></label><label>Your style<select name="style"><option ${selected('Classic',p.style)}>Classic</option><option ${selected('Modern',p.style)}>Modern</option><option ${selected('Casual',p.style)}>Casual</option><option ${selected('Feminine',p.style)}>Feminine</option><option ${selected('Western',p.style)}>Western</option><option ${selected('Minimal',p.style)}>Minimal</option></select></label><label>Typical outfit budget (NZ$)<input name="budget" type="number" min="50" value="${p.budget||300}"></label><label>Favourite colours<input name="colours" value="${p.colours||''}" placeholder="e.g. navy, green, cream"></label><label>Favourite retailers<input name="retailers" value="${p.retailers||''}" placeholder="e.g. Max, Country Road"></label><label class="wide">Anything you prefer to cover or avoid?<textarea name="avoid" placeholder="e.g. prefer sleeves, no low necklines">${p.avoid||''}</textarea></label><div class="wide actions"><button class="primary large" type="submit">Save profile & ask Suited</button></div></form></section>`;document.getElementById('pf').onsubmit=e=>{e.preventDefault();set('profile',Object.fromEntries(new FormData(e.target)));toast('Your Suited profile is saved');setTimeout(ask,350)}}

function summary(p){if(!p.size)return `<aside class="summary-card"><span class="eyebrow">PERSONALISE IT</span><h3>Create your profile first.</h3><p>Suited becomes more useful once it knows your size, style and budget.</p><button class="secondary" onclick="profile()">Build my profile</button></aside>`;return `<aside class="summary-card"><span class="eyebrow">SHOPPING AS</span><h3>Your Suited profile</h3><div class="summary-list"><div class="summary-item"><span>Size</span><strong>${p.size}</strong></div><div class="summary-item"><span>Style</span><strong>${p.style||'—'}</strong></div><div class="summary-item"><span>Fit</span><strong>${p.fit||'—'}</strong></div><div class="summary-item"><span>Budget</span><strong>NZ$${p.budget||300}</strong></div></div><div class="actions"><button class="secondary" onclick="profile()">Edit profile</button></div></aside>`}

function ask(){const p=get('profile',{});app.innerHTML=`<section class="ask-layout"><div class="panel"><span class="eyebrow">ASK SUITED</span><h1>What are you shopping for?</h1><p class="subtext">Describe it naturally. Suited will combine outfit inspiration with real retailer pieces that fit your brief.</p><textarea id="q" class="ask-input" placeholder="Try: I need a flattering winter wedding outfit under $350, including shoes and a bag."></textarea><div class="quick-prompts"><button onclick="q.value='Winter wedding under $350'">Winter wedding</button><button onclick="q.value='Casual lunch outfit under $250'">Casual lunch</button><button onclick="q.value='Saturday night outfit under $300'">Saturday night</button><button onclick="q.value='Smart work outfit under $350'">Work outfit</button></div><button class="primary large" onclick="results()">Find my looks →</button></div>${summary(p)}</section>`;updateBadge()}

function inferOccasion(q){return q.includes('wedding')||q.includes('event')?'wedding':q.includes('work')||q.includes('office')?'work':q.includes('night')||q.includes('dinner')?'night':'casual'}
function matchedProducts(key,budget,p){let list=products.filter(x=>x.occasion.includes(key)&&Math.min(x.sale||x.price,x.price)<=budget);const style=(p.style||'').toLowerCase();if(style)list.sort((a,b)=>Number(b.styles.includes(style))-Number(a.styles.includes(style)));if(!list.length)list=products.filter(x=>Math.min(x.sale||x.price,x.price)<=budget);return list.slice(0,4)}
function results(){const q=(document.getElementById('q')?.value||'casual outfit').toLowerCase(),p=get('profile',{}),budget=+(q.match(/\$(\d+)/)?.[1]||p.budget||999),key=inferOccasion(q);let m=looks.filter(x=>x.price<=Math.max(budget,250)&&x.occasion===key);if(!m.length)m=looks.filter(x=>x.occasion===key);if(!m.length)m=looks.slice(0,3);const real=matchedProducts(key,budget,p);app.innerHTML=`<section><div class="section-head"><div><span class="eyebrow">SUITED FOR YOU</span><h1>Your personal edit.</h1><p class="subtext">Matched to “${escapeHtml(q)}”${p.size?`, size ${p.size}`:''} and a budget around NZ$${budget}.</p></div><button class="secondary" onclick="ask()">New search</button></div><div class="looks-grid">${m.map(card).join('')}</div><div class="real-products"><div class="section-head compact"><div><span class="eyebrow">REAL PIECES TO SHOP</span><h2>Available from retailers now.</h2><p class="subtext">These are real retailer listings. Click through to confirm your size and current stock.</p></div></div>${real.length?`<div class="product-grid">${real.map(productCard).join('')}</div>`:`<div class="empty"><h2>No real products under that budget yet.</h2><p>Try a slightly higher budget while we expand the V1 retailer catalogue.</p></div>`}<p class="freshness-note">Product information is a live V1 snapshot and can change on retailer sites. Style-preview photography is illustrative and is not the retailer product image.</p></div></section>`;updateBadge()}

function card(x){const saved=get('saved',[]).includes(x.id);return `<article class="look-card"><div class="look-image photo"><img src="${x.image}" alt="Editorial style inspiration for ${x.name}" loading="lazy"><div class="image-shade"></div><span class="match">${x.score}% SUITED MATCH</span><span class="preview-label">STYLE INSPIRATION</span><div class="silhouette">${x.name}</div></div><div class="look-body"><h3>${x.name}</h3><p>${x.items.join(' · ')}</p><div class="price-row"><span class="price">Target NZ$${x.price}</span><span class="match-score">Complete look</span></div><div class="actions"><button class="${saved?'secondary':'primary'}" onclick="saveLook(${x.id})">${saved?'♥ Saved':'♡ Save look'}</button><button class="secondary" onclick="resultsFromLook('${x.occasion}')">Find real pieces</button></div></div></article>`}
function productCard(x){const display=x.sale||x.price;return `<article class="product-card"><div class="product-image"><img src="${x.image}" alt="Illustrative style preview" loading="lazy"><span class="preview-chip">STYLE PREVIEW</span><span class="retailer-chip">${x.retailer}</span></div><div class="product-body"><h3>${x.name}</h3><p class="product-meta">${x.colour} · Sizes ${x.sizes}</p><div class="product-price">${x.sale?`<strong>${money(x.sale)}</strong><del>${money(x.price)}</del>`:`<strong>${money(x.price)}</strong>`}</div><button class="primary retailer-button" onclick="shop('${x.url}')">View at ${x.retailer} ↗</button></div></article>`}
function resultsFromLook(occasion){const p=get('profile',{});app.innerHTML=`<section class="panel"><span class="eyebrow">REAL RETAILER PIECES</span><h1>Pieces for your ${occasion} look.</h1><p class="subtext">Choose a piece below, or ask Suited for a more specific brief.</p><div class="product-grid">${matchedProducts(occasion,Number(p.budget||999),p).map(productCard).join('')}</div><div class="actions"><button class="secondary" onclick="ask()">Refine with Ask Suited</button></div></section>`}
function saveLook(id){let s=get('saved',[]);if(s.includes(id)){s=s.filter(x=>x!==id);toast('Removed from saved looks')}else{s.push(id);toast('Saved to your lookbook')}set('saved',s);updateBadge();if(document.querySelector('.section-head')?.textContent.includes('Saved'))saved()}
function saved(){const ids=get('saved',[]),m=looks.filter(x=>ids.includes(x.id));app.innerHTML=`<section><div class="section-head"><div><span class="eyebrow">YOUR LOOKBOOK</span><h1>Saved looks.</h1><p class="subtext">Keep the outfits you love in one place.</p></div><button class="primary" onclick="ask()">Find another outfit</button></div>${m.length?`<div class="looks-grid">${m.map(card).join('')}</div>`:`<div class="empty"><h2>Your lookbook is waiting.</h2><p>Ask Suited for an outfit, then save the looks you love.</p><button class="primary" onclick="ask()">Ask Suited</button></div>`}</section>`;updateBadge()}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
home();