const app=document.getElementById('app');
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const looks=[
{id:1,name:'Emerald After Dark',style:'modern',occasion:'wedding',items:['Emerald midi dress','Black heel','Structured mini bag','Gold drop earrings'],price:329,score:96,visual:'wedding'},
{id:2,name:'Navy Occasion Edit',style:'classic',occasion:'wedding',items:['Navy wrap dress','Nude heel','Cream clutch','Pearl earrings'],price:298,score:93,visual:'classic'},
{id:3,name:'Soft Weekend',style:'casual',occasion:'casual',items:['Dark straight jeans','Cream knit','Leather loafer','Crossbody bag'],price:276,score:94,visual:'casual'},
{id:4,name:'Saturday Noir',style:'modern',occasion:'night',items:['Black straight jeans','Satin blouse','Heeled boot','Statement earrings'],price:289,score:97,visual:'night'},
{id:5,name:'The Polished Workday',style:'classic',occasion:'work',items:['Tailored trouser','Soft blouse','Loafer','Structured tote'],price:310,score:92,visual:'work'},
{id:6,name:'Lunch in Town',style:'feminine',occasion:'casual',items:['Midi skirt','Fine knit top','White sneaker','Shoulder bag'],price:245,score:91,visual:'feminine'}];
function updateBadge(){const b=document.getElementById('savedBadge');if(b)b.textContent=get('saved',[]).length}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function show(page){if(page==='profile')return profile();if(page==='ask')return ask();if(page==='saved')return saved();home()}
function home(){app.innerHTML=`<section class="hero"><div class="hero-copy"><span class="eyebrow">YOUR PERSONAL SHOPPING ASSISTANT</span><h1>Style that feels like <em>you.</em></h1><p>Build your profile once. Suited uses your size, fit preferences, style and budget to create complete looks — clothing, shoes, bags and jewellery — without the endless scrolling.</p><div class="actions"><button class="primary large" onclick="profile()">Build my style profile</button><button class="secondary large" onclick="ask()">Ask Suited</button></div><div class="trust-row"><span class="tag">NZ sizes 6–20</span><span class="tag">Complete outfits</span><span class="tag">Budget aware</span><span class="tag">Save your favourites</span></div></div><aside class="style-board"><div class="board-label"><span class="eyebrow">YOUR SUITED EDIT</span><h2>One profile.<br>Better shopping.</h2></div><div class="outfit-visual"><div class="fashion-tile main">A look selected around you</div><div class="fashion-tile">Shoes</div><div class="fashion-tile">Bag</div><div class="fashion-tile">Jewellery</div></div></aside></section>`;updateBadge()}
function selected(value,current){return String(value).toLowerCase()===String(current||'').toLowerCase()?'selected':''}
function profile(){const p=get('profile',{});app.innerHTML=`<section class="panel"><span class="eyebrow">MY SUITED PROFILE</span><h1>Tell us what works for you.</h1><p class="subtext">This becomes your personal shopping brief. You can change it whenever you like, and measurements are optional.</p><div class="profile-note">V1 keeps this information on this device only. A secure account system comes with the production version.</div><form id="pf" class="form"><label>Usual NZ clothing size<select name="size">${[6,8,10,12,14,16,18,20].map(x=>`<option ${selected(x,p.size)}>${x}</option>`).join('')}</select></label><label>Height (cm)<input name="height" inputmode="numeric" value="${p.height||''}" placeholder="e.g. 168"></label><label>Bust (cm) · optional<input name="bust" inputmode="numeric" value="${p.bust||''}"></label><label>Waist (cm) · optional<input name="waist" inputmode="numeric" value="${p.waist||''}"></label><label>Hips (cm) · optional<input name="hips" inputmode="numeric" value="${p.hips||''}"></label><label>Preferred fit<select name="fit"><option ${selected('Regular',p.fit)}>Regular</option><option ${selected('Relaxed',p.fit)}>Relaxed</option><option ${selected('Fitted',p.fit)}>Fitted</option></select></label><label>Your style<select name="style"><option ${selected('Classic',p.style)}>Classic</option><option ${selected('Modern',p.style)}>Modern</option><option ${selected('Casual',p.style)}>Casual</option><option ${selected('Feminine',p.style)}>Feminine</option><option ${selected('Western',p.style)}>Western</option><option ${selected('Minimal',p.style)}>Minimal</option></select></label><label>Typical outfit budget (NZ$)<input name="budget" type="number" min="50" value="${p.budget||300}"></label><label>Favourite colours<input name="colours" value="${p.colours||''}" placeholder="e.g. navy, green, cream"></label><label>Favourite retailers<input name="retailers" value="${p.retailers||''}" placeholder="e.g. Max, Country Road"></label><label class="wide">Anything you prefer to cover or avoid?<textarea name="avoid" placeholder="e.g. prefer sleeves, no low necklines">${p.avoid||''}</textarea></label><div class="wide actions"><button class="primary large" type="submit">Save profile & ask Suited</button></div></form></section>`;document.getElementById('pf').onsubmit=e=>{e.preventDefault();set('profile',Object.fromEntries(new FormData(e.target)));toast('Your Suited profile is saved');setTimeout(ask,350)}}
function summary(p){if(!p.size)return `<aside class="summary-card"><span class="eyebrow">PERSONALISE IT</span><h3>Create your profile first.</h3><p>Suited becomes more useful once it knows your size, style and budget.</p><button class="secondary" onclick="profile()">Build my profile</button></aside>`;return `<aside class="summary-card"><span class="eyebrow">SHOPPING AS</span><h3>Your Suited profile</h3><div class="summary-list"><div class="summary-item"><span>Size</span><strong>${p.size}</strong></div><div class="summary-item"><span>Style</span><strong>${p.style||'—'}</strong></div><div class="summary-item"><span>Fit</span><strong>${p.fit||'—'}</strong></div><div class="summary-item"><span>Budget</span><strong>NZ$${p.budget||300}</strong></div></div><div class="actions"><button class="secondary" onclick="profile()">Edit profile</button></div></aside>`}
function ask(){const p=get('profile',{});app.innerHTML=`<section class="ask-layout"><div class="panel"><span class="eyebrow">ASK SUITED</span><h1>What are you shopping for?</h1><p class="subtext">Describe it naturally. Tell Suited the occasion, budget, pieces you want or how you want to feel.</p><textarea id="q" class="ask-input" placeholder="Try: I need a flattering winter wedding outfit under $350, including shoes and a bag."></textarea><div class="quick-prompts"><button onclick="q.value='Winter wedding under $350'">Winter wedding</button><button onclick="q.value='Casual lunch outfit under $250'">Casual lunch</button><button onclick="q.value='Saturday night jeans and top under $300'">Saturday night</button><button onclick="q.value='Smart work outfit under $350'">Work outfit</button></div><button class="primary large" onclick="results()">Find my looks →</button></div>${summary(p)}</section>`;updateBadge()}
function results(){const q=(document.getElementById('q')?.value||'casual outfit').toLowerCase(),p=get('profile',{}),budget=+(q.match(/\$(\d+)/)?.[1]||p.budget||999);let key=q.includes('wedding')||q.includes('event')?'wedding':q.includes('work')||q.includes('office')?'work':q.includes('night')||q.includes('dinner')?'night':'casual';let m=looks.filter(x=>x.price<=budget&&x.occasion===key);if(!m.length)m=looks.filter(x=>x.price<=budget);if(!m.length)m=looks.slice(0,3);app.innerHTML=`<section><div class="section-head"><div><span class="eyebrow">SUITED FOR YOU</span><h1>Your personal edit.</h1><p class="subtext">Matched to “${escapeHtml(q)}”${p.size?`, size ${p.size}`:''} and a budget around NZ$${budget}.</p></div><button class="secondary" onclick="ask()">New search</button></div><div class="looks-grid">${m.map(card).join('')}</div></section>`;updateBadge()}
function card(x){const saved=get('saved',[]).includes(x.id);return `<article class="look-card"><div class="look-image ${x.visual}"><span class="match">${x.score}% SUITED MATCH</span><div class="silhouette">${x.name}</div></div><div class="look-body"><h3>${x.name}</h3><p>${x.items.join(' · ')}</p><div class="price-row"><span class="price">NZ$${x.price}</span><span class="match-score">Complete look</span></div><div class="actions"><button class="${saved?'secondary':'primary'}" onclick="saveLook(${x.id})">${saved?'♥ Saved':'♡ Save look'}</button><button class="secondary" onclick="shopLook(${x.id})">Shop look</button></div></div></article>`}
function saveLook(id){let s=get('saved',[]);if(s.includes(id)){s=s.filter(x=>x!==id);toast('Removed from saved looks')}else{s.push(id);toast('Saved to your lookbook')}set('saved',s);updateBadge();if(document.querySelector('.looks-grid')){const current=looks.filter(x=>s.includes(x.id));if(document.querySelector('.section-head')?.textContent.includes('Saved'))saved()}}
function shopLook(id){const x=looks.find(v=>v.id===id);toast(`${x.name}: retailer links are next to connect`)}
function saved(){const ids=get('saved',[]),m=looks.filter(x=>ids.includes(x.id));app.innerHTML=`<section><div class="section-head"><div><span class="eyebrow">YOUR LOOKBOOK</span><h1>Saved looks.</h1><p class="subtext">Keep the outfits you love in one place.</p></div><button class="primary" onclick="ask()">Find another outfit</button></div>${m.length?`<div class="looks-grid">${m.map(card).join('')}</div>`:`<div class="empty"><h2>Your lookbook is waiting.</h2><p>Ask Suited for an outfit, then save the looks you love.</p><button class="primary" onclick="ask()">Ask Suited</button></div>`}</section>`;updateBadge()}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
home();