const SuitedTesting={
  startedAt:null,
  sessionId:null,
  ensure(){this.sessionId=sessionStorage.getItem('suitedTestSession')||('test-'+Date.now()+'-'+Math.random().toString(36).slice(2,8));sessionStorage.setItem('suitedTestSession',this.sessionId);this.startedAt=this.startedAt||Date.now()},
  event(name,detail={}){this.ensure();const events=get('suitedTestEvents',[]);events.push({name,detail,at:new Date().toISOString(),session:this.sessionId});set('suitedTestEvents',events.slice(-250))},
  summary(){const events=get('suitedTestEvents',[]);return {sessions:new Set(events.map(x=>x.session)).size,profile:events.filter(x=>x.name==='profile_saved').length,searches:events.filter(x=>x.name==='search').length,saves:events.filter(x=>x.name==='look_saved').length,retailer:events.filter(x=>x.name==='retailer_click').length,tryon:events.filter(x=>x.name==='tryon_open').length,feedback:get('suitedFeedback',[]).length}},
  feedback(data){const all=get('suitedFeedback',[]);all.push({...data,at:new Date().toISOString(),session:this.sessionId});set('suitedFeedback',all);this.event('feedback',{rating:data.rating})}
};
SuitedTesting.ensure();SuitedTesting.event('visit');

function betaStart(){app.innerHTML=`<section class="panel beta-welcome"><span class="eyebrow">SUITED PRIVATE BETA</span><h1>Help us test a better way to shop.</h1><p class="subtext">Suited matches clothing to your size, style, budget and occasion. This is an early test, so some retailer stock can change and AI try-on is still being activated.</p><div class="beta-steps"><div><b>1</b><strong>Create your style profile</strong><span>About 2 minutes.</span></div><div><b>2</b><strong>Ask Suited for an outfit</strong><span>Use a real occasion you are shopping for.</span></div><div><b>3</b><strong>Save or shop something</strong><span>Tell us whether the recommendations helped.</span></div></div><div class="actions"><button class="primary large" onclick="SuitedTesting.event('beta_started');profile()">Start the 5-minute test →</button><button class="secondary" onclick="testerFeedback()">Give feedback</button></div><p class="freshness-note">Please don't enter information you don't want stored in your Suited account. Uploaded fitting-room photos stay on this device unless you explicitly request an AI try-on.</p></section>`}

function testerFeedback(){const p=get('profile',{});app.innerHTML=`<section class="panel feedback-panel"><span class="eyebrow">BETA FEEDBACK</span><h1>Would you use Suited again?</h1><p class="subtext">This is the most important part of the test. Tell us what genuinely worked and what didn't.</p><form id="feedbackForm" class="form"><label class="wide">Overall, how useful was Suited?<select name="rating" required><option value="">Choose…</option><option value="5">5 — Very useful</option><option value="4">4 — Useful</option><option value="3">3 — Okay</option><option value="2">2 — Not very useful</option><option value="1">1 — Not useful</option></select></label><label class="wide">Would you use Suited instead of searching several clothing websites?<select name="replaceSearch" required><option value="">Choose…</option><option>Yes</option><option>Maybe</option><option>No</option></select></label><label class="wide">Did you find something you would consider buying?<select name="buyIntent" required><option value="">Choose…</option><option>Yes</option><option>Maybe</option><option>No</option></select></label><label class="wide">What was the best part?<textarea name="best" placeholder="What saved you time or felt useful?"></textarea></label><label class="wide">What frustrated you or needs changing?<textarea name="problem" placeholder="Be as critical as you like."></textarea></label><label class="wide">What feature would make you come back?<textarea name="wanted"></textarea></label><button class="primary large wide">Send beta feedback</button></form></section>`;document.getElementById('feedbackForm').onsubmit=e=>{e.preventDefault();SuitedTesting.feedback(Object.fromEntries(new FormData(e.target)));app.innerHTML=`<section class="panel empty"><span class="eyebrow">THANK YOU</span><h1>Feedback saved.</h1><p>Your test has helped us decide what Suited should build next.</p><button class="primary" onclick="home()">Back to Suited</button></section>`}}

function testingDashboard(){const s=SuitedTesting.summary();app.innerHTML=`<section><div class="section-head"><div><span class="eyebrow">BETA TEST DASHBOARD</span><h1>What testers are doing.</h1><p class="subtext">Simple on-device V1 metrics. This avoids paid analytics while we validate demand.</p></div></div><div class="metric-grid"><div><strong>${s.sessions}</strong><span>Test sessions</span></div><div><strong>${s.searches}</strong><span>Outfit searches</span></div><div><strong>${s.saves}</strong><span>Looks saved</span></div><div><strong>${s.retailer}</strong><span>Retailer clicks</span></div><div><strong>${s.tryon}</strong><span>Try-on opens</span></div><div><strong>${s.feedback}</strong><span>Feedback forms</span></div></div><div class="panel test-goals"><h2>Early validation targets</h2><p><b>Strong signal:</b> 50%+ of testers complete a search, 25%+ click a retailer, and 60%+ say they would use Suited again or instead of searching multiple stores.</p><p><b>What matters most:</b> retailer clicks and genuine purchase intent — not page views.</p></div></section>`}

// Lightweight instrumentation around existing functions.
setTimeout(()=>{
  if(window.shop&&!window.shop.__tested){const old=window.shop;window.shop=function(url){SuitedTesting.event('retailer_click',{url});return old(url)};window.shop.__tested=true}
  if(window.results&&!window.results.__tested){const old=window.results;window.results=function(){SuitedTesting.event('search',{query:document.getElementById('q')?.value||''});return old()};window.results.__tested=true}
  if(window.saveLook&&!window.saveLook.__tested){const old=window.saveLook;window.saveLook=function(id){SuitedTesting.event('look_saved',{id});return old(id)};window.saveLook.__tested=true}
  if(window.tryOnProduct&&!window.tryOnProduct.__tested){const old=window.tryOnProduct;window.tryOnProduct=function(id){SuitedTesting.event('tryon_open',{id});return old(id)};window.tryOnProduct.__tested=true}
},500);
